name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set up tools in PATH
        run: |
          echo Setting PATH for NuGet and PAC CLI
          set PATH=C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          echo Checking NuGet version...
          C:\tools\nuget\nuget.exe
          echo Checking PAC CLI version...
          C:\tools\pac\Microsoft.PowerApps.CLI\tools\pac.exe help
        shell: cmd

      - name: Export Solution
        run: |
          set PATH=C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          C:\tools\pac\Microsoft.PowerApps.CLI\tools\pac.exe auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "125@Pqws@125"
          C:\tools\pac\Microsoft.PowerApps.CLI\tools\pac.exe solution export --name DemoSolution --path out\DemoSolution.zip
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        run: |
          set PATH=C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          C:\tools\pac\Microsoft.PowerApps.CLI\tools\pac.exe auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "125@Pqws@125"
          C:\tools\pac\Microsoft.PowerApps.CLI\tools\pac.exe solution publish
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
