name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      PATH: C:\tools\nuget;%PATH%

    steps:
      # Add NuGet to PATH (just to be safe)
      - name: Add NuGet to PATH
        run: |
          echo Adding NuGet to PATH
          set PATH=C:\tools\nuget;%PATH%
        shell: cmd

      # Install Power Platform CLI (PAC) using the official action
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Verify pac is installed (optional check)
      - name: Verify pac is installed
        run: pac help
        shell: cmd

      # Export Solution
      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://orge547d4f3.crm4.dynamics.com'
          user-name: 'Pragya.Khandelwal@wepa.eu'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: DemoSolution
          solution-output-file: 'DemoSolution.zip'
          working-directory: 'out'

      # Unpack Solution
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      # Publish Solution
      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://orge547d4f3.crm4.dynamics.com'
          user-name: 'Pragya.Khandelwal@wepa.eu'
          password-secret: ${{ secrets.PASSWORD }}

      # Prepare changes for source control check-in
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
