name: Power Platform DeploymentMore actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # ✅ Add NuGet to PATH before installing CLI tools
      - name: Add NuGet to PATH
        run: |
          set PATH=C:\tools\nuget;%PATH%
          echo "NuGet path added"
        shell: cmd

      # ✅ Install PAC using the action
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # ✅ Add PAC to PATH (in this session only)
      - name: Add PAC to PATH
        run: |
          echo "Adding PAC to PATH"
          setx PATH "%PATH%;C:\Users\runneradmin\.local\Microsoft\PowerAppsCLI"
          set PATH=%USERPROFILE%\.local\Microsoft\PowerAppsCLI;%PATH%
          echo "PAC path added: %USERPROFILE%\.local\Microsoft\PowerAppsCLI"
        shell: cmd

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://orge547d4f3.crm4.dynamics.com'
          user-name: 'Pragya.Khandelwal@wepa.eu'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: DemoSolution
          solution-output-file: 'DemoSolution.zip'
          working-directory: 'out'

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://orge547d4f3.crm4.dynamics.com'
          user-name: 'Pragya.Khandelwal@wepa.eu'
          password-secret: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
