name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # ✅ Step 1: Install NuGet, PAC CLI, and Export Solution
      - name: Install and Export Solution
        run: |
          echo Adding NuGet to PATH...
          set PATH=C:\tools\nuget;%PATH%

          echo Installing Power Platform CLI...
          nuget install Microsoft.PowerApps.CLI -OutputDirectory C:\tools\pac -Source https://api.nuget.org/v3/index.json -ExcludeVersion
          set PATH=C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%

          echo Authenticating with PAC CLI...
          pac auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "%PASSWORD%"

          echo Exporting solution...
          pac solution export --name DemoSolution --path out\DemoSolution.zip
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      # ✅ Step 2: Unpack the exported solution
      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      # ✅ Step 3: Publish the solution (optional but often recommended)
      - name: Publish Solution
        run: |
          set PATH=C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          pac auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "%PASSWORD%"
          pac solution publish
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      # ✅ Step 4: Branch and prepare unpacked solution for source control
      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
