name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install NuGet + PAC + Run Export
        run: |
          echo Installing NuGet and Power Platform CLI...

          set PATH=C:\tools\nuget;%PATH%

          echo Verifying NuGet:
          nuget help

          echo Installing PAC...
          nuget install Microsoft.PowerApps.CLI -OutputDirectory C:\tools\pac -Source https://api.nuget.org/v3/index.json -ExcludeVersion

          set PATH=C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          echo Verifying PAC:
          pac help

          echo Exporting solution...
          pac auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "%PASSWORD%"
          pac solution export --name DemoSolution --outputFile out\DemoSolution.zip
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        run: |
          set PATH=C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          pac auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "%PASSWORD%"
          pac solution publish
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
