name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Add PAC and NuGet to PATH
        run: |
          set PATH=C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          echo %PATH%
        shell: cmd

      - name: Check CLI versions
        run: |
          echo Checking nuget version...
          nuget
          echo Checking PAC CLI version...
          pac --version
        shell: cmd

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: 'https://orge547d4f3.crm4.dynamics.com'
          user-name: 'Pragya.Khandelwal@wepa.eu'
          password-secret: ${{ secrets.PASSWORD }}
          solution-name: DemoSolution
          solution-output-file: 'DemoSolution.zip'
          working-directory: 'out'

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v1
        with:
          environment-url: 'https://orge547d4f3.crm4.dynamics.com'
          user-name: 'Pragya.Khandelwal@wepa.eu'
          password-secret: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
