name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Export Solution using PAC CLI with Service Principal Auth
        run: |
          echo Adding NuGet and PAC to PATH...
          set PATH=C:\tools\nuget;C:\tools\pac;%PATH%

          echo Authenticating using Service Principal...
          pac auth create --client-id %CLIENT_ID% --client-secret %CLIENT_SECRET% --tenant %TENANT_ID% --environment https://orge547d4f3.crm4.dynamics.com --name mySPProfile

          echo Exporting solution...
          pac solution export --name DemoSolution --path out\DemoSolution.zip --publisher-prefix demo

        shell: cmd
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        run: |
          set PATH=C:\tools\pac;%PATH%
          pac auth select --name mySPProfile
          pac solution publish
        shell: cmd
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}

      - name: Prepare solution changes for check-in into source control
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
