name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check NuGet and PAC availability
        shell: powershell
        run: |
          $env:PATH = "C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;$env:PATH"
          Write-Host "Checking NuGet version..."
          nuget help
          Write-Host "Checking PAC CLI version..."
          pac help

      - name: Check secrets
        run: |
           if ($env:USERNAME) { Write-Host "USERNAME is set" } else { Write-Host "USERNAME is NOT set" }
           if ($env:PASSWORD) { Write-Host "PASSWORD is set" } else { Write-Host "PASSWORD is NOT set" }
        shell: powershell
        env:
           USERNAME: ${{ secrets.POWERPLATFORM_USERNAME }}
           PASSWORD: ${{ secrets.POWERPLATFORM_PASSWORD }}
       
      - name: Authenticate with Power Platform
        shell: powershell
        run: |
          $env:PATH = "C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;$env:PATH"
          pac auth clear
          pac auth create --environment https://orge547d4f3.crm4.dynamics.com --username pragya.khandelwal@wepa.eu --password 125@Pqws@125


      - name: Export Power Platform Solution
        shell: powershell
        run: |
          $env:PATH = "C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;$env:PATH"
          pac solution export --name DemoSolution --path out\DemoSolution.zip --managed false --overwrite

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        shell: powershell
        run: |
          $env:PATH = "C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;$env:PATH"
          pac solution publish

      - name: Prepare for Git Check-In
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
