name: Power Platform Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: '0'  # Use with caution, debug only

      - name: Check tools availability
        run: |
          set PATH=C:\tools\nuget;C:\tools\pac\Microsoft.PowerApps.CLI\tools;%PATH%
          git --version
          nuget
          pac help
        shell: cmd

      - name: Verify tools
        run: |
          echo Checking NuGet version...
          nuget
          echo Checking PAC CLI version...
          pac help
        shell: cmd

      - name: Authenticate and Export Solution
        run: |
          pac auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "%PASSWORD%"
          pac solution export --name DemoSolution --path out\DemoSolution.zip
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: 'out/DemoSolution.zip'
          solution-folder: 'out/solutions/DemoSolution'
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Publish Solution
        run: |
          pac auth create --url https://orge547d4f3.crm4.dynamics.com --username "Pragya.Khandelwal@wepa.eu" --password "%PASSWORD%"
          pac solution publish
        shell: cmd
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Prepare solution changes for check-in
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: 'out/solutions/DemoSolution'
          solution-target-folder: 'src/solutions/DemoSolution'
          token: ${{ secrets.POWERPLATFORM_TOKEN }}
